### ISSUE TITLE
Sometimes fails to open PowerShell

### ISSUE THREAD

**Issue by ThatCoolCoder** [cfsamson/powershell-script#5]
Weirdly, even though PowerShell is on my path, it fails with the error "The system could not find the file specified" (not exact, from memory) if I run it in `cmd` - such as when a compiled Rust executable is double-clicked from explorer. This is quite annoying as my app's main use case is to be double-clicked from explorer. I don't really blame this library though as PowerShell is on my path and it should be getting picked up, so it's the fault of Windows.

I'll probably make a PR soon with the functionality that if it fails to launch `powershell` it tries to launch `C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe`.

**Comment by ThatCoolCoder** [comment]
I've now created a PR that fixes (or at least improves) this issue: #6

**Comment by cfsamson** [comment]
Just wanted to follow up on this, since the root cause was recently fixed in #13. It turns out that a difference between how linux and windows resolves paths in "PATH" caused the program to often fail to find the PowerShell version in PATH. More specifically we tried to walk the dirs in PATH and find one that matches "PATH\PowerShell" but we should have searched for "PATH\PowerShell.exe".

The library should now work as expected and resolve any PowerShell versions that's in PATH 👍
